const SW_VERSION='mf-v41-153';const PRECACHE=SW_VERSION+'-precache';const RUNTIME=SW_VERSION+'-runtime';const DATA_CACHE='mf-data-v1';const PRECACHE_URLS=['/','/index.html','/og-preview.jpg','/manifest.json'];self.addEventListener('install',event=>{event.waitUntil(caches.open(PRECACHE).then(cache=>Promise.all(PRECACHE_URLS.map(url=>cache.add(url).catch(err=>console.warn('[sw] precache skip',url,err.message))))));});self.addEventListener('activate',event=>{event.waitUntil((async()=>{const keys=await caches.keys();await Promise.all(keys.filter(k=>k.startsWith('mf-v41-')&&k!==PRECACHE&&k!==RUNTIME).map(k=>caches.delete(k)));await self.clients.claim();})());});self.addEventListener('fetch',event=>{const req=event.request;if(req.method!=='GET')return;const url=new URL(req.url);if(url.pathname.startsWith('/api/')||url.search.includes('admin='))return;if(url.pathname.includes('stock.xlsx')||url.pathname.includes('stock.json')||url.pathname.includes('sitemap')){event.respondWith(fetch(req).catch(()=>caches.match(req)));return;}
const isVersionedData=(url.pathname.endsWith('/catalog.js')||url.pathname.includes('/catalog-data/'))&&/(^|[?&])v=/.test(url.search);if(isVersionedData){event.respondWith((async()=>{const cache=await caches.open(DATA_CACHE);const hit=await cache.match(req);if(hit)return hit;try{const resp=await fetch(url.href,{cache:'default'});if(resp&&resp.status===200){event.waitUntil((async()=>{await cache.put(req,resp.clone());const keys=await cache.keys();await Promise.all(keys.filter(k=>{const u=new URL(k.url);return u.pathname===url.pathname&&u.search!==url.search;}).map(k=>cache.delete(k)));})().catch(()=>{}));}
return resp;}catch(_){const any=(await cache.keys()).find(k=>new URL(k.url).pathname===url.pathname);if(any)return cache.match(any);throw _;}})());return;}
const isCatalogData=url.pathname.endsWith('/catalog.js')||url.pathname.includes('/catalog-data/');if(isCatalogData){event.respondWith(fetch(req).then(resp=>{if(resp&&resp.status===200){const copy=resp.clone();event.waitUntil(caches.open(RUNTIME).then(cache=>cache.put(req,copy)).catch(()=>{}));}else if(resp&&resp.status>=500){return caches.match(req).then(r=>r||resp);}
return resp;}).catch(()=>caches.match(req)));return;}
const isHTML=req.headers.get('accept')?.includes('text/html')||url.pathname.endsWith('/')||url.pathname.endsWith('.html');if(isHTML){event.respondWith(fetch(req).then(resp=>{if(resp&&resp.ok){const copy=resp.clone();event.waitUntil(caches.open(RUNTIME).then(cache=>cache.put(req,copy)).catch(()=>{}));}else if(resp&&resp.status>=500){return caches.match(req).then(r=>r||resp);}
return resp;}).catch(()=>caches.match(req).then(r=>r||caches.match('/index.html'))));return;}
if(url.origin===self.location.origin){event.respondWith(caches.match(req).then(cached=>{const fetchPromise=fetch(req).then(resp=>{if(resp&&resp.status===200){const copy=resp.clone();event.waitUntil(caches.open(RUNTIME).then(cache=>cache.put(req,copy)).catch(()=>{}));}
return resp;}).catch(()=>cached);if(cached)event.waitUntil(fetchPromise.catch(()=>{}));return cached||fetchPromise;}));return;}
event.respondWith(caches.match(req).then(cached=>{if(cached)return cached;return fetch(req).then(resp=>{if(resp&&(resp.status===200||resp.type==='opaque')){const copy=resp.clone();event.waitUntil(caches.open(RUNTIME).then(cache=>cache.put(req,copy)).catch(()=>{}));}
return resp;}).catch(()=>cached);}));});self.addEventListener('message',event=>{if(event.data&&event.data.type==='SKIP_WAITING')self.skipWaiting();});